version: '3.8'

services:
  api:
    build: .
    container_name: flask-api-container
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    command: python app.py

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
